apiVersion: apps/v1
kind: Deployment
metadata: 
  name: hasher-deploy
spec:
  replicas: 2
  selector: 
    matchLabels: 
      app: hasher-label
  template:
    metadata: 
      labels:
        app: hasher-label
    spec:
      containers:
        -
          image: carlosprietorebollo/ibm-dockercoins:latest-hasher
          name: hasher-container
          ports: 
            -
              containerPort: 8080
              protocol: TCP
