apiVersion: apps/v1
kind: Deployment
metadata: 
  name: worker-deploy
spec:
  replicas: 2
  selector: 
    matchLabels: 
      app: worker-label
  template:
    metadata: 
      labels:
        app: worker-label
    spec:
      containers:
        -
          image: carlosprietorebollo/ibm-dockercoins:latest-worker
          name: worker-container
